### ISSUE TITLE
[Feature] Add Reels Stats

### ISSUE THREAD

**Issue by IbraFal** [fivetran/dbt_instagram_business#8]
### Is there an existing feature request for this?

- [X] I have searched the existing issues

### Describe the Feature

The current package doesn't allow passthrough metrics neither it has reels stats making it difficult to measure KPIs on reels (they are no longer considered as videos by meta)

### Are you interested in contributing this feature?

- [x] Yes.
- [ ] Yes, but I will need assistance and will schedule time during your [office hours](https://calendly.com/fivetran-solutions-team/fivetran-solutions-team-office-hours) for guidance.
- [ ] No.

**Comment by fivetran-joemarkiewicz** [comment]
Hi @IbraFal thanks so much for opening this feature request and already getting started on a PR to contribute! I believe this is a valuable addition to the package, especially with Meta changing how reels are recorded in the underlying data.

Looking at your PR, it seems you are on the right track to include the relevant fields to the staging model. In addition to this, you will likely want to incorporate the fields in the downstream [instagram_business__posts](https://github.com/fivetran/dbt_instagram_business/blob/main/models/instagram_business__posts.sql) model. Would you be interested in also opening a PR to incorporate these models downstream?

Additionally, do you feel there is any need to include the reel stats in the aggregated [Social Media Reporting package](https://github.com/fivetran/dbt_social_media_reporting)? If so, we will want to figure out the further downstream impacts. If not, we should be able to take the approach of incorporating the fields in the platform specific models. In the meantime, I will investigate if adding these fields will have any other downstream implications. 

Thanks again for opening this feature and starting on the PR! 🎉

**Comment by IbraFal** [comment]
Hi @fivetran-joemarkiewicz  

I opened the PR on the downstream project. 

Thanks

**Comment by fivetran-joemarkiewicz** [comment]
Hi @IbraFal I just wanted to post back here that I have reviewed your two PRs and they generally look great! There are a few minor edits I want to make (just to ensure the changes work for all customers). Do you have any issues if I make some minor changes to your branch before merging?

Additionally, I noticed that for my data I am seeing the `reel_comment` field as `reel_comments` which is causing an error on my side. I am checking with our product team to see if I just have an older connector, or if the field is in fact `reel_comments`. Would you be able to confirm you see this field as `reel_comment`?

**Comment by IbraFal** [comment]
Hello @fivetran-joemarkiewicz , no worries you can go ahead and make the changes.  

As per your question I have  `reel_comments`  on my end. 
![Screenshot 2023-06-16 at 15 39 25](https://github.com/fivetran/dbt_instagram_business/assets/33211196/fd485f48-79fd-4939-81dd-42a1aa4b818e)

Thanks again for taking the time to review the PR.

**Comment by fivetran-joemarkiewicz** [comment]
Sounds great, thanks for confirming and will update on my end to reflect the data being synced.

**Comment by fivetran-joemarkiewicz** [comment]
Thanks again for all your hard work on integrating these updates into the package @IbraFal! 

As of the latest release, these are now included. You can expect these releases to be live at the top of the hour on the dbt hub! Thanks again for your contribution 😄
